apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-example
  labels:
    app: spring-profile-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-profile-example
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: spring-profile-example
    spec:
      containers:
      - name: spring-profile-example
        image: spring-profile-example
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: spring-profile-example-service
spec:
  selector:
    app: spring-profile-example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-profile-example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fvc-loc.angecom.cl
    http:
      paths:
      - path: /
        backend:
          serviceName: spring-profile-example-service
          servicePort: 80
